name: 'WM Design Studios '
favicon: null
layout_spectrum: 0.15323443221859634
typography_spectrum: 0.059802847914397717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7534042510669678
  lightness: 0.9443958641495556
  saturation: 0.8971155779436231
  rhythmicContrast: 0.15407191938720644
purpose: []
